name: Particle System CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm test
      
    - name: Run linting
      run: npm run lint

  performance-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run performance tests
      run: |
        npm run perf:test
      env:
        PARTICLE_COUNT: 10000
        TEST_DURATION: 60
    
    - name: Generate performance report
      run: npm run perf:report
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: perf-results/
        retention-days: 14

    - name: Check performance thresholds
      run: |
        npm run perf:check-thresholds
      env:
        MIN_FPS: 60
        MAX_MEMORY_USAGE: 512
        MAX_CPU_USAGE: 80

  benchmark:
    needs: performance-tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run benchmarks
      run: |
        npm run benchmark:particle-system
      env:
        BENCHMARK_ITERATIONS: 1000
        PARTICLES_PER_ITERATION: 1000
    
    - name: Compare with baseline
      run: npm run benchmark:compare
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark-results/
        retention-days: 14

  visual-regression:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run visual regression tests
      run: |
        npm run test:visual-regression
      env:
        PARTICLE_SCENARIOS: "explosion,sparkle,smoke"
    
    - name: Upload visual diff results
      uses: actions/upload-artifact@v3
      with:
        name: visual-regression-results
        path: visual-regression-results/
        retention-days: 14